### ISSUE TITLE
Add to the description all the sources that are compatible

### ISSUE THREAD

**Issue by Hedronmx** [bernardodsanderson/vido#19]
Just what the title says, let the user know what sources work.

**Comment by bernardodsanderson** [comment]
Great idea, I'll try to add those for the next release. The ElementaryOS team didn't like me using marketing material that mentions places like YouTube and Vimeo for copyright concerns, but I might just add a link. Meanwhile, if you're curious, here's the list: https://rg3.github.io/youtube-dl/supportedsites.html
