### ISSUE TITLE
Does not seem to download audio, might be older version of Youtube-dl?

### ISSUE THREAD

**Issue by CallieG** [bernardodsanderson/vido#20]
As the title states, I cannot get Vido to download anything using the "audio only" option.

I removed it, and along with it went youtube-dl.  Can I assume that's the repo version?

It's been out of date for a while, and it never works correctly for me.

However, the version here: https://rg3.github.io/youtube-dl/download.html seems to work perfectly every time.

**Comment by bernardodsanderson** [comment]
Hi @CallieG, you're right, this is a bug. The youtube-dl that the app install is the repo version, so it might be that it's so outdated that it might not be working correctly. Thanks for letting me know, I'll do some investigation on how to fix it.

**Comment by bernardodsanderson** [comment]
Fixed is now live in the app store.
