### ISSUE TITLE
Add Releases Data

### ISSUE THREAD

**Issue by danrabbit** [bernardodsanderson/vido#21]
I'm marking the latest release of Vido as "Needs Fixing" because the AppData file doesn't seem to have been updated with any releases information.

Without the releases tag, there won't be any changelog visible to users in AppCenter. Please see the [appstream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases) for more information

**Comment by bernardodsanderson** [comment]
Thanks for pointing that out @danrabbit, pushed a fix for it.
