### ISSUE TITLE
Won't be accepted in AppCenter

### ISSUE THREAD

**Issue by cassidyjames** [bernardodsanderson/vido#6]
Just giving you a heads up that as-is, this app would violate the [AppCenter legal requirements](https://github.com/elementary/houston/wiki/Before-You-Publish) since it is designed to download copyrighted content from services that explicitly disallow that in their terms of service.

**Comment by bernardodsanderson** [comment]
@cassidyjames, thanks for the heads up. This app allows to download from legal places like archive.org too, would it help if I took out all references to places that have copyrighted content? I guess I originally thought this might be in the same area as Torrential.

**Comment by cassidyjames** [comment]
@bernardodsanderson yeah I think the issue is that it advertises/encourages you to download from copyrighted places (thus breaking their Terms of Service). I think if you remove those references it would be fine.

That's a good point regarding Torrential, and I think the difference is definitely in intent and how it's advertised. After all, you can use a web browser to do illegal stuff, but it's not the advertised intent of the app.
